# Frequently Changed Settings

# HOST_OS the host OS
# TARGET_OS the target OS
# TARGET_ARCH the target architecture
# COMPILER the host compiler

# Name of the libraries and executable
LIBRARY_CPP_NAME = example

# build lists
PROGRAM_CPP_CONTRIB_LIST = 
PROGRAM_CPP_EXAMPLE_LIST = 

# LIBRARY COMPILE INCLUDE DIRECTORY
# PREPEND -I"
# APPEND "
LIBRARY_CPP_COMPILE_INCLUDE_DIR = include
# PREPEND -I"$(PROJECT_HOME_DIR_PREFIX)/
# APPEND "
LIBRARY_CPP_COMPILE_INCLUDE_DIR_PROJECT = include
# PREPEND -I"
# APPEND /$(VERSION_NAME)"
LIBRARY_CPP_COMPILE_INCLUDE_DIR_VERSION = include
# PREPEND -I"$(PROJECT_HOME_DIR_PREFIX)/
# APPEND /$(VERSION_NAME)"
LIBRARY_CPP_COMPILE_INCLUDE_DIR_PROJECT_VERSION = include

# LIBRARY LINK LIBRARY DIRECTORY
# PREPEND -L"
# APPEND "
LIBRARY_CPP_LINK_LIB_DIR = lib
# PREPEND -L"$(PROJECT_HOME_DIR_PREFIX)/
# APPEND "
LIBRARY_CPP_LINK_LIB_DIR_PROJECT = lib
# PREPEND -L"
# APPEND /$(VERSION_NAME)"
LIBRARY_CPP_LINK_LIB_DIR_VERSION = lib
# PREPEND -L"$(PROJECT_HOME_DIR_PREFIX)/
# APPEND /$(VERSION_NAME)"
LIBRARY_CPP_LINK_LIB_DIR_PROJECT_VERSION = lib

# LIBRARY LINK LIBRARY FILE
# PREPEND -l"
# APPEND "
LIBRARY_CPP_LINK_LIB_FILE = 
# PREPEND -l"
# APPEND $(BOOST_LIBS_POST)"
LIBRARY_CPP_LINK_LIB_FILE_VERSION_BOOST = boost_filesystem boost_thread boost_locale boost_system boost_iostreams

# PROGRAM COMPILE INCLUDE DIRECTORY
# PREPEND -I"
# APPEND "
PROGRAM_CPP_COMPILE_INCLUDE_DIR = include
# PREPEND -I"$(PROJECT_HOME_DIR_PREFIX)/
# APPEND "
PROGRAM_CPP_COMPILE_INCLUDE_DIR_PROJECT = include
# PREPEND -I"
# APPEND /$(VERSION_NAME)"
PROGRAM_CPP_COMPILE_INCLUDE_DIR_VERSION = include
# PREPEND -I"$(PROJECT_HOME_DIR_PREFIX)/
# APPEND /$(VERSION_NAME)"
PROGRAM_CPP_COMPILE_INCLUDE_DIR_PROJECT_VERSION = include

# PROGRAM LINK LIBRARY DIRECTORY
# PREPEND -L"
# APPEND "
PROGRAM_CPP_LINK_LIB_DIR = lib bin
# PREPEND -L"$(PROJECT_HOME_DIR_PREFIX)/
# APPEND "
PROGRAM_CPP_LINK_LIB_DIR_PROJECT = lib bin
# PREPEND -L"
# APPEND /$(VERSION_NAME)"
PROGRAM_CPP_LINK_LIB_DIR_VERSION = lib bin
# PREPEND -L"$(PROJECT_HOME_DIR_PREFIX)/
# APPEND /$(VERSION_NAME)"
PROGRAM_CPP_LINK_LIB_DIR_PROJECT_VERSION = lib bin

# PROGRAM LINK LIBRARY FILE
# PREPEND -l"
# APPEND "
PROGRAM_CPP_LINK_LIB_FILE = 
# PREPEND -l"
# APPEND $(BOOST_LIBS_POST)"
PROGRAM_CPP_LINK_LIB_FILE_VERSION_BOOST = boost_filesystem boost_thread boost_locale boost_system boost_iostreams

# Build OneHeader utility
PROGRAM_ONE_HEADER_BUILD_FLAG=0
# Use OneHeader utility to create a single include header
PROGRAM_ONE_HEADER_USE_FLAG=0
# Make Static Library
LIBRARY_CPP_STATIC_BIN_FLAG=0
# Make Shared Library
LIBRARY_CPP_SHARED_BIN_FLAG=0
# Make Executable
LIBRARY_CPP_EXE_BIN_FLAG=1
# Make contributed libraries (typically they are dependencies too)
PROGRAM_CPP_CONTRIB_FLAG=0
# Make example programs
PROGRAM_CPP_EXAMPLE_FLAG=0